### ISSUE TITLE
URGENT Still unable to send forgotten password accounts

### ISSUE THREAD

**Issue by eehan87** [sean0x42/riverrats.com.au#114] opened 2018-10-25 12:59 UTC
Trying to send the forgotten password or reset password email to kozzmikk@hotmail.com for user account @shelycameron and it's still not working.

I'm also unable to set new accounts as admin for Shely to be able to do her scores.

**Comment by sean0x42** [comment] 2018-10-25 14:22
Duplicate of #105, closing

**Closed by sean0x42** 2018-10-25 14:22 UTC
Labels: bug
